# 2.) GIVENS METHOD

In [2]:
import time

start_time = time.time()

import numpy as np
import math

# Define the matrix A
#A = np.array([[3, 1, 1], [1, 3, 2], [1, 2, 3] ])   another example 
A = np.array([[1, 2, 1, 2], [2, 2, -1, 1], [1, -1, 1, 1], [2, 1, 1, 1]])
n = 4  # size of square matrix A

# Initialize the unitary matrix Q as the identity matrix
Q = np.eye(n)

# Tri-diagonalize A using the Givens method
for i in range(0, A.shape[0]):
    for j in range(i + 1, A.shape[0] - 1):
        r = i    # row index r
        p = i + 1    # row index p
        q = j + 1    # column index q
        
        # Calculate the rotation angle in degrees and radians
        theta_degrees = math.degrees(math.atan(A[r, q] / A[r, r + 1]))
        theta_radians = math.radians(theta_degrees)
        
        # Calculate the sin and cos of the rotation angle
        sin_theta = math.sin(theta_radians)
        cos_theta = math.cos(theta_radians)
        
        # Initialize Q as the identity matrix before applying the Givens rotation
        Q = np.eye(A.shape[0])
        
        # Populate the matrix Q with values for the current Givens rotation
        Q[p, p] = cos_theta
        Q[p, q] = sin_theta
        Q[q, p] = -sin_theta
        Q[q, q] = cos_theta
        
        # Update matrix A by applying the Givens rotation using matrix multiplication
        A = np.dot(Q, np.dot(A, Q.T))
        
        # Print the updated matrix A
        print(A.round(decimals=4))

# Negate the off-diagonal elements in the last two rows and columns of A
A[n - 1][n - 2] = -(A[n - 1][n - 2])
A[n - 2][n - 1] = -(A[n - 2][n - 1])
A[n - 4][n - 3] = -(A[n - 4][n - 3])
A[n - 3][n - 4] = -(A[n - 3][n - 4])

#Number of iterations or rotations required in Givens method 
k = ((n*n)-((n)+2*(n-1)))/2


# Print the final tridiagonal matrix A
print(f"The Number of Iterations required for Given's method is : {k}")
print(A.round(decimals=4))


end_time = time.time()

elapsed_time = end_time - start_time

print(f"Elapsed time: {elapsed_time:.4f} seconds")

[[ 1.      2.2361  0.      2.    ]
 [ 2.2361  1.     -1.      1.3416]
 [ 0.     -1.      2.      0.4472]
 [ 2.      1.3416  0.4472  1.    ]]
[[ 1.      3.      0.      0.    ]
 [ 3.      2.3333 -0.4472  0.1491]
 [ 0.     -0.4472  2.      1.    ]
 [ 0.      0.1491  1.     -0.3333]]
[[ 1.      3.      0.      0.    ]
 [ 3.      2.3333 -0.4714 -0.    ]
 [ 0.     -0.4714  1.1667  1.5   ]
 [ 0.     -0.      1.5     0.5   ]]
The Number of Iterations required for Given's method is : 3.0
[[ 1.     -3.      0.      0.    ]
 [-3.      2.3333 -0.4714 -0.    ]
 [ 0.     -0.4714  1.1667 -1.5   ]
 [ 0.     -0.     -1.5     0.5   ]]
Elapsed time: 0.0218 seconds


# Eigenvectors of Tridiagonalized matrix

In [3]:

import numpy as np
print(A.round(decimals=4))

# Calculate eigenvalues and eigenvectors of matrix A
eigenvals, eigenvecs = np.linalg.eig(A)

# Print the eigenvalues
print("Eigenvalues of A:")
print(eigenvals)


# Print eigenvectors
print("\nEigenvectors:")
print(eigenvecs)

[[ 1.     -3.      0.      0.    ]
 [-3.      2.3333 -0.4714 -0.    ]
 [ 0.     -0.4714  1.1667 -1.5   ]
 [ 0.     -0.     -1.5     0.5   ]]
Eigenvalues of A:
[ 4.78378005  2.34968353 -1.4658573  -0.66760628]

Eigenvectors:
[[ 0.61635818  0.1212607  -0.74892336 -0.21097923]
 [-0.77738793 -0.05455453 -0.61557938 -0.11727676]
 [ 0.11852485 -0.76980622 -0.19502003  0.59608508]
 [-0.04150243  0.624274   -0.14880533  0.76577836]]


# Eigenvectors of covariance matrix

In [1]:
import numpy as np

# Define the matrix B
B = np.array([[1, 2,1,2], [2,2,-1,1], [1,-1,1,1],[2,1,1,1]])

# Calculate eigenvalues and eigenvectors
eigenvalsB, eigenvecsB = np.linalg.eig(B)

# Print eigenvalues
print("Eigenvalues:")
print(eigenvalsB)

# Print eigenvectors
print("\nEigenvectors:")
print(eigenvecsB)


Eigenvalues:
[ 4.78378005  2.34968353 -1.4658573  -0.66760628]

Eigenvectors:
[[ 0.61635818  0.1212607   0.74892336 -0.21097923]
 [ 0.57554185 -0.58650376 -0.46964085 -0.32280396]
 [ 0.14738301  0.74396511 -0.38905977 -0.52290215]
 [ 0.51684855  0.29635299 -0.25919833  0.76017018]]


# By observing the eigen values obtained from the final tridiagonalized matrix we can say that we have successfully implemented the GIVENS Method

In [44]:
print(A.round(decimals=4))
print(eigenvecs)

[[ 1.     -3.      0.      0.    ]
 [-3.      2.3333 -0.4714 -0.    ]
 [ 0.     -0.4714  1.1667 -1.5   ]
 [ 0.     -0.     -1.5     0.5   ]]
[[ 0.61635818  0.1212607  -0.74892336 -0.21097923]
 [-0.77738793 -0.05455453 -0.61557938 -0.11727676]
 [ 0.11852485 -0.76980622 -0.19502003  0.59608508]
 [-0.04150243  0.624274   -0.14880533  0.76577836]]


In [61]:
print(Q.round(decimals=4))

[[ 1.      0.      0.      0.    ]
 [ 0.      1.      0.      0.    ]
 [ 0.      0.      0.9487 -0.3162]
 [ 0.      0.      0.3162  0.9487]]


# The above matrix Q is the Givens Rotaion matrix used in the last Iteration

# We know that if x is an eigenvector of A, then y = T_inverse.x is an eigenvector of Â

In [5]:
T_inverse = np.linalg.inv(Q)
print(T_inverse)
Y = np.dot(T_inverse, eigenvecsB)
print(Y.round(decimals=4))

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.9486833   0.31622777]
 [ 0.          0.         -0.31622777  0.9486833 ]]
[[ 0.6164  0.1213  0.7489 -0.211 ]
 [ 0.5755 -0.5865 -0.4696 -0.3228]
 [ 0.3033  0.7995 -0.4511 -0.2557]
 [ 0.4437  0.0459 -0.1229  0.8865]]


# The eigenvectors obtained in the above cell following the above stated theorem are similar to the Eigenvectors of Tridiagonalized matrix so we can say that the y= T_inverse. x relation is satisfied