# 1.) HOUSEHOLDER METHOD

In [2]:
import time

start_time = time.time()

import numpy as np

A = np.array([[1, 2, 1, 2], 
              [2, 2, -1, 1], 
              [1, -1, 1, 1], 
              [2, 1, 1, 1]])
n = 4

# Make a copy of the input matrix
temp1 = np.copy(A)

# Perform Householder's method
for r in range(n-2):
    # Print the current row of the temporary matrix
    print()
    print(temp1[r])
    # Make a copy of the current row
    x = np.copy(temp1[r])
    print(x)
    # Calculate s
    sum = 0
    for i in range(r+1, n):
        sum += x[i]**2
    s = np.sqrt(sum)
    # Calculate alpha, v, and w
    alpha = 1 / np.sqrt(2 * s * (s + x[r+1]))
    v = x[r+1] + s
    w = np.zeros(n)
    w[r+1] = v
    for i in range(r+2, n):
        w[i] = x[i]
    # Print the values of s, v, alpha, and w
    print("for", r, "iteration:")
    print("s value: ", s)
    print("v value: ", v)
    print("alpha value: ", alpha)
    print("W matrix values: ", w)
    # Scale w by alpha
    w = w * alpha
    # Compute ww, t, and tt
    ww = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            ww[i][j] = 2 * w[i] * w[j]
    id = np.eye(n)
    t = id - ww
    tt = np.transpose(t)
    # Compute it and temp2
    it = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            for k in range(n):
                it[i][j] += t[i][k] * temp1[k][j]
    temp2 = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            for k in range(n):
                temp2[i][j] += it[i][k] * tt[k][j]
    # Make temp2 the new temporary matrix
    temp1 = np.copy(temp2)
    # Print the updated temporary matrix
    print(temp1.round(decimals=4))

# Print the number of iterations required for Householder's method
print("Number of iterations required for Householder's method is:", n-2)


end_time = time.time()

elapsed_time = end_time - start_time

print(f"Elapsed time: {elapsed_time:.4f} seconds")


[1 2 1 2]
[1 2 1 2]
for 0 iteration:
s value:  3.0
v value:  5.0
alpha value:  0.18257418583505536
W matrix values:  [0. 5. 1. 2.]
[[ 1.     -3.      0.      0.    ]
 [-3.      2.3333  0.4667 -0.0667]
 [ 0.      0.4667  1.5733  1.3467]
 [ 0.     -0.0667  1.3467  0.0933]]

[-3.          2.33333333  0.46666667 -0.06666667]
[-3.          2.33333333  0.46666667 -0.06666667]
for 1 iteration:
s value:  0.4714045207910315
v value:  0.9380711874576979
alpha value:  1.0633353013601898
W matrix values:  [ 0.          0.          0.93807119 -0.06666667]
[[ 1.     -3.     -0.      0.    ]
 [-3.      2.3333 -0.4714 -0.    ]
 [-0.     -0.4714  1.1667 -1.5   ]
 [ 0.     -0.     -1.5     0.5   ]]
Number of iterations required for Householder's method is: 2
Elapsed time: 0.0197 seconds


# Number of iterations required for Householder's method is: 2

# Eigenvectors of Tridiagonalized matrix

In [3]:
import numpy as np
print(temp1.round(decimals=4))

# Calculate eigenvalues and eigenvectors of matrix temp1
eigenvals, eigenvecs = np.linalg.eig(temp1)

# Print the eigenvalues
print("Eigenvalues of Tridiagonalized matrix:")
print(eigenvals)


# Print eigenvectors
print("\nEigenvectors of Tridiagonalized matrix:")
print(eigenvecs)

[[ 1.     -3.     -0.      0.    ]
 [-3.      2.3333 -0.4714 -0.    ]
 [-0.     -0.4714  1.1667 -1.5   ]
 [ 0.     -0.     -1.5     0.5   ]]
Eigenvalues of Tridiagonalized matrix:
[ 4.78378005  2.34968353 -1.4658573  -0.66760628]

Eigenvectors of Tridiagonalized matrix:
[[ 0.61635818 -0.1212607  -0.74892336 -0.21097923]
 [-0.77738793  0.05455453 -0.61557938 -0.11727676]
 [ 0.11852485  0.76980622 -0.19502003  0.59608508]
 [-0.04150243 -0.624274   -0.14880533  0.76577836]]


# Eigenvectors of covariance matrix

In [4]:
import numpy as np

# Define the matrix A
A = np.array([[1, 2,1,2], [2,2,-1,1], [1,-1,1,1],[2,1,1,1]])

# Calculate eigenvalues and eigenvectors of matrix A
eigenvals1, eigenvecs1 = np.linalg.eig(A)

# Print the eigenvalues
print("Eigenvalues of original matrix:")
print(eigenvals1)

# Print eigenvectors
print("\nEigenvectors of original matrix:")
print(eigenvecs1)


Eigenvalues of original matrix:
[ 4.78378005  2.34968353 -1.4658573  -0.66760628]

Eigenvectors of original matrix:
[[ 0.61635818  0.1212607   0.74892336 -0.21097923]
 [ 0.57554185 -0.58650376 -0.46964085 -0.32280396]
 [ 0.14738301  0.74396511 -0.38905977 -0.52290215]
 [ 0.51684855  0.29635299 -0.25919833  0.76017018]]


# By observing  eigen values obtained from the final tridiagonalized matrix and comparing with the eigen values of original covariance matrix we can say that we have successfully implemented the Householder Method

In [5]:
print(t.round(decimals=4))

[[ 1.      0.      0.      0.    ]
 [ 0.      1.      0.      0.    ]
 [ 0.      0.     -0.9899  0.1414]
 [ 0.      0.      0.1414  0.9899]]


# The above matrix T is the Householder transformation used in the last Iteration

# We know that if x is an eigenvector of A, then y = T_inverse.x is an eigenvector of Â

In [6]:
T_inverse = np.linalg.inv(t)
print(T_inverse)
y = np.dot(T_inverse, eigenvecs1)
print(y.round(decimals=4))

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [-0.         -0.         -0.98994949  0.14142136]
 [ 0.          0.          0.14142136  0.98994949]]
[[ 0.6164  0.1213  0.7489 -0.211 ]
 [ 0.5755 -0.5865 -0.4696 -0.3228]
 [-0.0728 -0.6946  0.3485  0.6252]
 [ 0.5325  0.3986 -0.3116  0.6786]]


# The eigenvectors obtained in the above cell following the above stated theorem are similar to the Eigenvectors of Tridiagonalized matrix so we can say that the y= T_inverse. x relation is satisfied. 